package manager

import "time"

// TaskState defines the current status of a Map or Reduce task.
//
// State transitions are strictly controlled via the DDS to ensure linearizability
// across Manager restarts or network partitions.
//
// State transitions:
//   - Idle -> InProgress (via GetNextTask)
//   - InProgress -> Completed (via CompleteTask)
//   - InProgress -> Idle (via FailTask for retries)
type TaskState int

const (
	// Idle means the task is ready to be assigned to a worker.
	Idle TaskState = iota
	// InProgress means a worker has been assigned and a lease is active.
	InProgress
	// Completed means the worker finished successfully and results are persisted.
	Completed
	// Failed means the task exceeded its maximum retry attempts.
	Failed
)

func (s TaskState) String() string {
	switch s {
	case Idle:
		return "Idle"
	case InProgress:
		return "InProgress"
	case Completed:
		return "Completed"
	case Failed:
		return "Failed"
	default:
		return "Unknown"
	}
}

// TaskType defines whether a task is a Map or Reduce task.
type TaskType int

const (
	// MapTask represents a mapper operation.
	MapTask TaskType = iota
	// ReduceTask represents a reducer operation.
	ReduceTask
)

func (t TaskType) String() string {
	switch t {
	case MapTask:
		return "MapTask"
	case ReduceTask:
		return "ReduceTask"
	default:
		return "Unknown"
	}
}

// TaskInputSplit represents a segment of an input file assigned to a Map task.
type TaskInputSplit struct {
	InputURI      string
	ByteStart     int64
	ByteEnd       int64
	SplitChecksum string
}

// TaskOutputRef points to the output generated by a completed task.
type TaskOutputRef struct {
	PartitionIndex int
	OutputURI      string
	Checksum       string
}

// ScheduleTaskInput is the input definition for scheduling a new task.
type ScheduleTaskInput struct {
	InputURI      string
	ByteStart     int64
	ByteEnd       int64
	SplitChecksum string
}

// ScheduleTask contains the initial metadata for a task during job creation.
type ScheduleTask struct {
	TaskID       string
	TaskType     string
	ReplicaIndex int
	InputSplits  []ScheduleTaskInput
}

// ScheduleJobRequest encapsulates all parameters required to launch a MapReduce job.
type ScheduleJobRequest struct {
	JobID         string
	UserID        string
	InputURI      string
	MapperURI     string
	ReducerURI    string
	CombinerURI   string
	MTasks        int
	RTasks        int
	InputChecksum string
	Tasks         []ScheduleTask
}

// SystemConfigUpdate represents a request to update cluster-wide resource limits.
type SystemConfigUpdate struct {
	MaxConcurrentPods int
	CPULimit          string
	MemoryLimit       string
}

// Task represents the metadata the Master needs to track for a single unit of work.
//
// It contains both immutable configuration and mutable execution state (e.g., active attempt, lease).
type Task struct {
	ID              string
	JobID           string
	Type            TaskType // MapTask or ReduceTask
	State           TaskState
	workerID        string
	InputFile       string
	ByteStart       int64
	ByteEnd         int64
	PartitionIndex  int
	CodeURI         string
	CombinerURI     string // Optional combiner code location for local pre-aggregation
	InputChecksum   string
	InputSplits     []TaskInputSplit
	ShuffleInputs   []TaskOutputRef
	ReplicaIndex    int // Manager StatefulSet replica binding (DDS TASKS.replica_index)
	ReducePartition int // Logical reduce partition identifier.
	TotalReducers   int // Number of reduce partitions (R) — map workers need this for hash(k) % R
	startTime       time.Time
	ActiveAttemptID string
	LeaseID         string
	LastHeartbeat   time.Time
	OutputURIs      []string
	OutputChecksums []string
	Attempts        int
	LastFailure     string
	LastFailedAt    time.Time
}

// TaskTracker tracks the overall job progress by storing the current
// map and reduce task metadata for a job.
//
// This is primarily used for in-memory projections during the job creation flow.
type TaskTracker struct {
	mapTasks    []Task
	reduceTasks []Task
}

// WorkerID returns the ID of the worker currently assigned to this task.
func (t *Task) WorkerID() string { return t.workerID }

// StartTime returns when the current task attempt was initiated.
func (t *Task) StartTime() time.Time { return t.startTime }

// GetAttemptID returns the UUID of the active attempt, used as a fencing token.
func (t *Task) GetAttemptID() string { return t.ActiveAttemptID }

// GetLeaseID returns the unique lease identifier for the current attempt.
func (t *Task) GetLeaseID() string { return t.LeaseID }

// GetHeartbeat returns the timestamp of the last successful worker heartbeat.
func (t *Task) GetHeartbeat() time.Time { return t.LastHeartbeat }

// Clone returns a deep copy of the Task metadata.
// This ensures that internal slices (OutputURIs and OutputChecksums) are
// copied to new underlying arrays, preventing external mutation.
func (t *Task) Clone() Task {
	clone := *t
	if t.InputSplits != nil {
		clone.InputSplits = make([]TaskInputSplit, len(t.InputSplits))
		copy(clone.InputSplits, t.InputSplits)
	}
	if t.OutputURIs != nil {
		clone.OutputURIs = make([]string, len(t.OutputURIs))
		copy(clone.OutputURIs, t.OutputURIs)
	}
	if t.ShuffleInputs != nil {
		clone.ShuffleInputs = make([]TaskOutputRef, len(t.ShuffleInputs))
		copy(clone.ShuffleInputs, t.ShuffleInputs)
	}
	if t.OutputChecksums != nil {
		clone.OutputChecksums = make([]string, len(t.OutputChecksums))
		copy(clone.OutputChecksums, t.OutputChecksums)
	}
	return clone
}

// NewTaskTracker safely initializes a TaskTracker by maintaining defensive copies.
func NewTaskTracker(mapTasks, reduceTasks []Task) *TaskTracker {
	mCopy := make([]Task, len(mapTasks))
	for i := range mapTasks {
		mCopy[i] = mapTasks[i].Clone()
	}
	rCopy := make([]Task, len(reduceTasks))
	for i := range reduceTasks {
		rCopy[i] = reduceTasks[i].Clone()
	}
	return &TaskTracker{
		mapTasks:    mCopy,
		reduceTasks: rCopy,
	}
}

// MapTaskCount returns the number of map tasks tracked.
func (tt *TaskTracker) MapTaskCount() int { return len(tt.mapTasks) }

// ReduceTaskCount returns the number of reduce tasks tracked.
func (tt *TaskTracker) ReduceTaskCount() int { return len(tt.reduceTasks) }

// JobState defines the current lifecycle state of a full MapReduce job.
type JobState int

const (
	// JobPending means the job is created but no tasks have been scheduled yet.
	JobPending JobState = iota
	// JobRunning means at least one task is being executed.
	JobRunning
	// JobCleaning means all tasks are finished and workers are being terminated.
	JobCleaning
	// JobCompleted means the job finished successfully and results are available.
	JobCompleted
	// JobFailed means the job was aborted due to excessive task failures.
	JobFailed
	// JobCancelled means the job was stopped by a user request.
	JobCancelled
)

func (s JobState) String() string {
	switch s {
	case JobPending:
		return "Pending"
	case JobRunning:
		return "Running"
	case JobCleaning:
		return "Cleaning"
	case JobCompleted:
		return "Completed"
	case JobFailed:
		return "Failed"
	case JobCancelled:
		return "Cancelled"
	default:
		return "Unknown"
	}
}

// JobRecord represents the overarching tracking record for a MapReduce execution.
type JobRecord struct {
	JobID            string
	State            JobState
	TotalMapTasks    int
	TotalReduceTasks int
	Tracker          *TaskTracker
}
