FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /manager ./manager-service/cmd/manager

FROM busybox:1.37
COPY --from=builder /manager /manager
EXPOSE 50051
ENTRYPOINT ["/manager"]
