// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/mapreduce.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Register_FullMethodName     = "/mapreduce.WorkerService/Register"
	WorkerService_Heartbeat_FullMethodName    = "/mapreduce.WorkerService/Heartbeat"
	WorkerService_TaskComplete_FullMethodName = "/mapreduce.WorkerService/TaskComplete"
	WorkerService_TaskFailed_FullMethodName   = "/mapreduce.WorkerService/TaskFailed"
	WorkerService_TaskStream_FullMethodName   = "/mapreduce.WorkerService/TaskStream"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService is the gRPC API used by worker pods to communicate with the Manager.
// Authentication: all RPCs must include the worker token in gRPC metadata:
//
//	"x-worker-token": <value of MANAGER_WORKER_RPC_TOKEN secret>
//
// The Manager enforces this via a server-side unary/stream interceptor.
// Omitting the token results in codes.Unauthenticated.
type WorkerServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*TaskAssignment, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	TaskComplete(ctx context.Context, in *TaskCompleteRequest, opts ...grpc.CallOption) (*Ack, error)
	TaskFailed(ctx context.Context, in *TaskFailedRequest, opts ...grpc.CallOption) (*Ack, error)
	TaskStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, StreamResponse], error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*TaskAssignment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskAssignment)
	err := c.cc.Invoke(ctx, WorkerService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, WorkerService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) TaskComplete(ctx context.Context, in *TaskCompleteRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, WorkerService_TaskComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) TaskFailed(ctx context.Context, in *TaskFailedRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, WorkerService_TaskFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) TaskStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_TaskStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_TaskStreamClient = grpc.BidiStreamingClient[StreamRequest, StreamResponse]

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService is the gRPC API used by worker pods to communicate with the Manager.
// Authentication: all RPCs must include the worker token in gRPC metadata:
//
//	"x-worker-token": <value of MANAGER_WORKER_RPC_TOKEN secret>
//
// The Manager enforces this via a server-side unary/stream interceptor.
// Omitting the token results in codes.Unauthenticated.
type WorkerServiceServer interface {
	Register(context.Context, *RegisterRequest) (*TaskAssignment, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	TaskComplete(context.Context, *TaskCompleteRequest) (*Ack, error)
	TaskFailed(context.Context, *TaskFailedRequest) (*Ack, error)
	TaskStream(grpc.BidiStreamingServer[StreamRequest, StreamResponse]) error
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Register(context.Context, *RegisterRequest) (*TaskAssignment, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWorkerServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerServiceServer) TaskComplete(context.Context, *TaskCompleteRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskComplete not implemented")
}
func (UnimplementedWorkerServiceServer) TaskFailed(context.Context, *TaskFailedRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskFailed not implemented")
}
func (UnimplementedWorkerServiceServer) TaskStream(grpc.BidiStreamingServer[StreamRequest, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method TaskStream not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_TaskComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).TaskComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_TaskComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).TaskComplete(ctx, req.(*TaskCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_TaskFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).TaskFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_TaskFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).TaskFailed(ctx, req.(*TaskFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_TaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).TaskStream(&grpc.GenericServerStream[StreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_TaskStreamServer = grpc.BidiStreamingServer[StreamRequest, StreamResponse]

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mapreduce.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WorkerService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _WorkerService_Heartbeat_Handler,
		},
		{
			MethodName: "TaskComplete",
			Handler:    _WorkerService_TaskComplete_Handler,
		},
		{
			MethodName: "TaskFailed",
			Handler:    _WorkerService_TaskFailed_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TaskStream",
			Handler:       _WorkerService_TaskStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/mapreduce.proto",
}

const (
	ShuffleService_PushShuffleData_FullMethodName = "/mapreduce.ShuffleService/PushShuffleData"
	ShuffleService_GetShuffleData_FullMethodName  = "/mapreduce.ShuffleService/GetShuffleData"
)

// ShuffleServiceClient is the client API for ShuffleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShuffleService handles intermediate MapReduce shuffle data exchange between workers.
// Authentication: same "x-worker-token" metadata requirement as WorkerService.
type ShuffleServiceClient interface {
	PushShuffleData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ShuffleDataChunk, Ack], error)
	GetShuffleData(ctx context.Context, in *ShuffleDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShuffleDataChunk], error)
}

type shuffleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShuffleServiceClient(cc grpc.ClientConnInterface) ShuffleServiceClient {
	return &shuffleServiceClient{cc}
}

func (c *shuffleServiceClient) PushShuffleData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ShuffleDataChunk, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShuffleService_ServiceDesc.Streams[0], ShuffleService_PushShuffleData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShuffleDataChunk, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShuffleService_PushShuffleDataClient = grpc.ClientStreamingClient[ShuffleDataChunk, Ack]

func (c *shuffleServiceClient) GetShuffleData(ctx context.Context, in *ShuffleDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShuffleDataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShuffleService_ServiceDesc.Streams[1], ShuffleService_GetShuffleData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShuffleDataRequest, ShuffleDataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShuffleService_GetShuffleDataClient = grpc.ServerStreamingClient[ShuffleDataChunk]

// ShuffleServiceServer is the server API for ShuffleService service.
// All implementations must embed UnimplementedShuffleServiceServer
// for forward compatibility.
//
// ShuffleService handles intermediate MapReduce shuffle data exchange between workers.
// Authentication: same "x-worker-token" metadata requirement as WorkerService.
type ShuffleServiceServer interface {
	PushShuffleData(grpc.ClientStreamingServer[ShuffleDataChunk, Ack]) error
	GetShuffleData(*ShuffleDataRequest, grpc.ServerStreamingServer[ShuffleDataChunk]) error
	mustEmbedUnimplementedShuffleServiceServer()
}

// UnimplementedShuffleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShuffleServiceServer struct{}

func (UnimplementedShuffleServiceServer) PushShuffleData(grpc.ClientStreamingServer[ShuffleDataChunk, Ack]) error {
	return status.Error(codes.Unimplemented, "method PushShuffleData not implemented")
}
func (UnimplementedShuffleServiceServer) GetShuffleData(*ShuffleDataRequest, grpc.ServerStreamingServer[ShuffleDataChunk]) error {
	return status.Error(codes.Unimplemented, "method GetShuffleData not implemented")
}
func (UnimplementedShuffleServiceServer) mustEmbedUnimplementedShuffleServiceServer() {}
func (UnimplementedShuffleServiceServer) testEmbeddedByValue()                        {}

// UnsafeShuffleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShuffleServiceServer will
// result in compilation errors.
type UnsafeShuffleServiceServer interface {
	mustEmbedUnimplementedShuffleServiceServer()
}

func RegisterShuffleServiceServer(s grpc.ServiceRegistrar, srv ShuffleServiceServer) {
	// If the following call panics, it indicates UnimplementedShuffleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShuffleService_ServiceDesc, srv)
}

func _ShuffleService_PushShuffleData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShuffleServiceServer).PushShuffleData(&grpc.GenericServerStream[ShuffleDataChunk, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShuffleService_PushShuffleDataServer = grpc.ClientStreamingServer[ShuffleDataChunk, Ack]

func _ShuffleService_GetShuffleData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ShuffleDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShuffleServiceServer).GetShuffleData(m, &grpc.GenericServerStream[ShuffleDataRequest, ShuffleDataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShuffleService_GetShuffleDataServer = grpc.ServerStreamingServer[ShuffleDataChunk]

// ShuffleService_ServiceDesc is the grpc.ServiceDesc for ShuffleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShuffleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mapreduce.ShuffleService",
	HandlerType: (*ShuffleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushShuffleData",
			Handler:       _ShuffleService_PushShuffleData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetShuffleData",
			Handler:       _ShuffleService_GetShuffleData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mapreduce.proto",
}
