// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/mapreduce.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_MAP    TaskType = 0
	TaskType_REDUCE TaskType = 1
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "MAP",
		1: "REDUCE",
	}
	TaskType_value = map[string]int32{
		"MAP":    0,
		"REDUCE": 1,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mapreduce_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_mapreduce_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{0}
}

type HeartbeatResponse_Action int32

const (
	HeartbeatResponse_CONTINUE  HeartbeatResponse_Action = 0
	HeartbeatResponse_TERMINATE HeartbeatResponse_Action = 1
)

// Enum value maps for HeartbeatResponse_Action.
var (
	HeartbeatResponse_Action_name = map[int32]string{
		0: "CONTINUE",
		1: "TERMINATE",
	}
	HeartbeatResponse_Action_value = map[string]int32{
		"CONTINUE":  0,
		"TERMINATE": 1,
	}
)

func (x HeartbeatResponse_Action) Enum() *HeartbeatResponse_Action {
	p := new(HeartbeatResponse_Action)
	*p = x
	return p
}

func (x HeartbeatResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeartbeatResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mapreduce_proto_enumTypes[1].Descriptor()
}

func (HeartbeatResponse_Action) Type() protoreflect.EnumType {
	return &file_proto_mapreduce_proto_enumTypes[1]
}

func (x HeartbeatResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeartbeatResponse_Action.Descriptor instead.
func (HeartbeatResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{3, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RegisterRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type TaskAssignment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId        string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	JobId            string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type             TaskType               `protobuf:"varint,4,opt,name=type,proto3,enum=mapreduce.TaskType" json:"type,omitempty"`
	CodeLocation     string                 `protobuf:"bytes,5,opt,name=code_location,json=codeLocation,proto3" json:"code_location,omitempty"`
	CombinerLocation string                 `protobuf:"bytes,6,opt,name=combiner_location,json=combinerLocation,proto3" json:"combiner_location,omitempty"`
	RuntimeEnv       string                 `protobuf:"bytes,7,opt,name=runtime_env,json=runtimeEnv,proto3" json:"runtime_env,omitempty"`
	DataLocations    []string               `protobuf:"bytes,8,rep,name=data_locations,json=dataLocations,proto3" json:"data_locations,omitempty"`
	ByteStart        int64                  `protobuf:"varint,9,opt,name=byte_start,json=byteStart,proto3" json:"byte_start,omitempty"`
	ByteEnd          int64                  `protobuf:"varint,10,opt,name=byte_end,json=byteEnd,proto3" json:"byte_end,omitempty"`
	PartitionId      int32                  `protobuf:"varint,11,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	IsManifest       bool                   `protobuf:"varint,12,opt,name=is_manifest,json=isManifest,proto3" json:"is_manifest,omitempty"`
	TotalReducers    int32                  `protobuf:"varint,13,opt,name=total_reducers,json=totalReducers,proto3" json:"total_reducers,omitempty"`
	SplitChecksum    string                 `protobuf:"bytes,14,opt,name=split_checksum,json=splitChecksum,proto3" json:"split_checksum,omitempty"`
	LeaseId          string                 `protobuf:"bytes,15,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_proto_mapreduce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{1}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskAssignment) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_MAP
}

func (x *TaskAssignment) GetCodeLocation() string {
	if x != nil {
		return x.CodeLocation
	}
	return ""
}

func (x *TaskAssignment) GetCombinerLocation() string {
	if x != nil {
		return x.CombinerLocation
	}
	return ""
}

func (x *TaskAssignment) GetRuntimeEnv() string {
	if x != nil {
		return x.RuntimeEnv
	}
	return ""
}

func (x *TaskAssignment) GetDataLocations() []string {
	if x != nil {
		return x.DataLocations
	}
	return nil
}

func (x *TaskAssignment) GetByteStart() int64 {
	if x != nil {
		return x.ByteStart
	}
	return 0
}

func (x *TaskAssignment) GetByteEnd() int64 {
	if x != nil {
		return x.ByteEnd
	}
	return 0
}

func (x *TaskAssignment) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *TaskAssignment) GetIsManifest() bool {
	if x != nil {
		return x.IsManifest
	}
	return false
}

func (x *TaskAssignment) GetTotalReducers() int32 {
	if x != nil {
		return x.TotalReducers
	}
	return 0
}

func (x *TaskAssignment) GetSplitChecksum() string {
	if x != nil {
		return x.SplitChecksum
	}
	return ""
}

func (x *TaskAssignment) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HeartbeatRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *HeartbeatRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Action        HeartbeatResponse_Action `protobuf:"varint,1,opt,name=action,proto3,enum=mapreduce.HeartbeatResponse_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_mapreduce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAction() HeartbeatResponse_Action {
	if x != nil {
		return x.Action
	}
	return HeartbeatResponse_CONTINUE
}

type TaskCompleteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId       string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LeaseId         string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	OutputLocations []string               `protobuf:"bytes,4,rep,name=output_locations,json=outputLocations,proto3" json:"output_locations,omitempty"`
	OutputChecksums []string               `protobuf:"bytes,5,rep,name=output_checksums,json=outputChecksums,proto3" json:"output_checksums,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskCompleteRequest) Reset() {
	*x = TaskCompleteRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleteRequest) ProtoMessage() {}

func (x *TaskCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleteRequest.ProtoReflect.Descriptor instead.
func (*TaskCompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{4}
}

func (x *TaskCompleteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCompleteRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskCompleteRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TaskCompleteRequest) GetOutputLocations() []string {
	if x != nil {
		return x.OutputLocations
	}
	return nil
}

func (x *TaskCompleteRequest) GetOutputChecksums() []string {
	if x != nil {
		return x.OutputChecksums
	}
	return nil
}

type TaskFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"` // Fencing: Manager rejects stale failures
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFailedRequest) Reset() {
	*x = TaskFailedRequest{}
	mi := &file_proto_mapreduce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFailedRequest) ProtoMessage() {}

func (x *TaskFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFailedRequest.ProtoReflect.Descriptor instead.
func (*TaskFailedRequest) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{5}
}

func (x *TaskFailedRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskFailedRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskFailedRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TaskFailedRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_mapreduce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mapreduce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_mapreduce_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_mapreduce_proto protoreflect.FileDescriptor

const file_proto_mapreduce_proto_rawDesc = "" +
	"\n" +
	"\x15proto/mapreduce.proto\x12\tmapreduce\"I\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\"\x89\x04\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.mapreduce.TaskTypeR\x04type\x12#\n" +
	"\rcode_location\x18\x05 \x01(\tR\fcodeLocation\x12+\n" +
	"\x11combiner_location\x18\x06 \x01(\tR\x10combinerLocation\x12\x1f\n" +
	"\vruntime_env\x18\a \x01(\tR\n" +
	"runtimeEnv\x12%\n" +
	"\x0edata_locations\x18\b \x03(\tR\rdataLocations\x12\x1d\n" +
	"\n" +
	"byte_start\x18\t \x01(\x03R\tbyteStart\x12\x19\n" +
	"\bbyte_end\x18\n" +
	" \x01(\x03R\abyteEnd\x12!\n" +
	"\fpartition_id\x18\v \x01(\x05R\vpartitionId\x12\x1f\n" +
	"\vis_manifest\x18\f \x01(\bR\n" +
	"isManifest\x12%\n" +
	"\x0etotal_reducers\x18\r \x01(\x05R\rtotalReducers\x12%\n" +
	"\x0esplit_checksum\x18\x0e \x01(\tR\rsplitChecksum\x12\x19\n" +
	"\blease_id\x18\x0f \x01(\tR\aleaseId\"e\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\"w\n" +
	"\x11HeartbeatResponse\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.mapreduce.HeartbeatResponse.ActionR\x06action\"%\n" +
	"\x06Action\x12\f\n" +
	"\bCONTINUE\x10\x00\x12\r\n" +
	"\tTERMINATE\x10\x01\"\xbe\x01\n" +
	"\x13TaskCompleteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12)\n" +
	"\x10output_locations\x18\x04 \x03(\tR\x0foutputLocations\x12)\n" +
	"\x10output_checksums\x18\x05 \x03(\tR\x0foutputChecksums\"\x8b\x01\n" +
	"\x11TaskFailedRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x1f\n" +
	"\bTaskType\x12\a\n" +
	"\x03MAP\x10\x00\x12\n" +
	"\n" +
	"\x06REDUCE\x10\x012\x96\x02\n" +
	"\rWorkerService\x12A\n" +
	"\bRegister\x12\x1a.mapreduce.RegisterRequest\x1a\x19.mapreduce.TaskAssignment\x12F\n" +
	"\tHeartbeat\x12\x1b.mapreduce.HeartbeatRequest\x1a\x1c.mapreduce.HeartbeatResponse\x12>\n" +
	"\fTaskComplete\x12\x1e.mapreduce.TaskCompleteRequest\x1a\x0e.mapreduce.Ack\x12:\n" +
	"\n" +
	"TaskFailed\x12\x1c.mapreduce.TaskFailedRequest\x1a\x0e.mapreduce.AckB\x15Z\x13kubemapreduce/protob\x06proto3"

var (
	file_proto_mapreduce_proto_rawDescOnce sync.Once
	file_proto_mapreduce_proto_rawDescData []byte
)

func file_proto_mapreduce_proto_rawDescGZIP() []byte {
	file_proto_mapreduce_proto_rawDescOnce.Do(func() {
		file_proto_mapreduce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mapreduce_proto_rawDesc), len(file_proto_mapreduce_proto_rawDesc)))
	})
	return file_proto_mapreduce_proto_rawDescData
}

var file_proto_mapreduce_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_mapreduce_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_mapreduce_proto_goTypes = []any{
	(TaskType)(0),                 // 0: mapreduce.TaskType
	(HeartbeatResponse_Action)(0), // 1: mapreduce.HeartbeatResponse.Action
	(*RegisterRequest)(nil),       // 2: mapreduce.RegisterRequest
	(*TaskAssignment)(nil),        // 3: mapreduce.TaskAssignment
	(*HeartbeatRequest)(nil),      // 4: mapreduce.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 5: mapreduce.HeartbeatResponse
	(*TaskCompleteRequest)(nil),   // 6: mapreduce.TaskCompleteRequest
	(*TaskFailedRequest)(nil),     // 7: mapreduce.TaskFailedRequest
	(*Ack)(nil),                   // 8: mapreduce.Ack
}
var file_proto_mapreduce_proto_depIdxs = []int32{
	0, // 0: mapreduce.TaskAssignment.type:type_name -> mapreduce.TaskType
	1, // 1: mapreduce.HeartbeatResponse.action:type_name -> mapreduce.HeartbeatResponse.Action
	2, // 2: mapreduce.WorkerService.Register:input_type -> mapreduce.RegisterRequest
	4, // 3: mapreduce.WorkerService.Heartbeat:input_type -> mapreduce.HeartbeatRequest
	6, // 4: mapreduce.WorkerService.TaskComplete:input_type -> mapreduce.TaskCompleteRequest
	7, // 5: mapreduce.WorkerService.TaskFailed:input_type -> mapreduce.TaskFailedRequest
	3, // 6: mapreduce.WorkerService.Register:output_type -> mapreduce.TaskAssignment
	5, // 7: mapreduce.WorkerService.Heartbeat:output_type -> mapreduce.HeartbeatResponse
	8, // 8: mapreduce.WorkerService.TaskComplete:output_type -> mapreduce.Ack
	8, // 9: mapreduce.WorkerService.TaskFailed:output_type -> mapreduce.Ack
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mapreduce_proto_init() }
func file_proto_mapreduce_proto_init() {
	if File_proto_mapreduce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mapreduce_proto_rawDesc), len(file_proto_mapreduce_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mapreduce_proto_goTypes,
		DependencyIndexes: file_proto_mapreduce_proto_depIdxs,
		EnumInfos:         file_proto_mapreduce_proto_enumTypes,
		MessageInfos:      file_proto_mapreduce_proto_msgTypes,
	}.Build()
	File_proto_mapreduce_proto = out.File
	file_proto_mapreduce_proto_goTypes = nil
	file_proto_mapreduce_proto_depIdxs = nil
}
