apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: keycloak-partition
  namespace: mapreduce
spec:
  action: partition
  mode: all
  selector:
    labelSelectors:
      app: keycloak
  direction: both
  target:
    selector:
      labelSelectors:
        app: kubemapreduce-manager
    mode: all
  duration: "45s"
